# Generated by Django 3.1.5 on 2021-01-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210107_2134'),
        ('users', '0002_auto_20200901_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_book_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_book', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_movie_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_movie', to='categories.category'),
        ),
    ]
