# Generated by Django 3.1.5 on 2021-01-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210107_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_book_genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('history', 'History')], default='history', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_movie_genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('history', 'History')], default='history', max_length=20),
        ),
    ]
