# Generated by Django 3.1.5 on 2021-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210107_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('bookmovie', 'Book and Movie')], default='bookmovie', max_length=10),
        ),
    ]
