# Generated by Django 3.1.5 on 2021-01-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20210107_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
